### ISSUE TITLE
Google Calendar can't add swedish verison

### ISSUE THREAD

**Issue by C4illin** [EdvinNilsson/chalmersCalendar#2]
Hello and thanks for this! I cant add the swedish version to google calendar but the english version works fine, I tried multiple computers and google accounts. Do you know any fix?

**Comment by EdvinNilsson** [comment]
It looks like this is a problem on Google's side. A workaround is to use https://edvinnilsson.se/chalmers.ics instead which is just a redirect to the swedish url.
